name: Docker Build & Push - light-bot

on:
  push:
    branches: [ "light-bot", "dev" ]
  workflow_dispatch:

jobs:
  build-and-push-light:
    if: github.ref_name == 'light-bot'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and push image (light-bot)
      uses: docker/build-push-action@v5
      with:
        push: true
        tags: |
          ${{ secrets.DOCKERHUB_USERNAME }}/light-bot:light-bot
          ${{ secrets.DOCKERHUB_USERNAME }}/light-bot:${{ github.sha }}

  build-and-push-dev:
    if: github.ref_name == 'dev'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and push image (dev)
      uses: docker/build-push-action@v5
      with:
        push: true
        tags: |
          ${{ secrets.DOCKERHUB_USERNAME }}/light-bot:dev
          ${{ secrets.DOCKERHUB_USERNAME }}/light-bot:${{ github.sha }}
